### PR TITLE
Add zoom

### PR DESCRIPTION
**Pull request by ielijose**
- Prettier
- Zoom canvas

Live: https://react-flow-chart.now.sh/?path=/story/other-config--zoom

### CODE REVIEW

**Comment by nandurnair** [comment]
Really interested to see the zoom capability.

But prettier and docs and some build files buried the zoom feature code.  All in one commit is making it really hard to read.

**Comment by ielijose** [comment]
> Really interested to see the zoom capability.
> 
> But prettier and docs and some build files buried the zoom feature code. All in one commit is making it really hard to read.

Hi, thanks for the feedback, I'll fix that.

**Comment by ielijose** [comment]
@nandurnair can you review now?

Thank you

**Comment by hayaah** [comment]
Hi, I have been looking for a similar feature and was happy to see it being developed 
but there is a bug in it, its caused by react-zoom-pan-pinch
please check attached link
[attachment](https://drive.google.com/file/d/1nOXBWD7-YQSpCbk2drG1QV-3vOJW07T_/view)

**Pull request merged**
